#!/usr/bin/env sh

if [ ! -z "$CRON_CONTAINER" ]; then
    echo "*       *       *       *       *       run-parts /etc/periodic/1min" >> /etc/crontabs/root
    exec crond -f -l 8
else

    if [ ! -z "$WWWUSER" ]; then
        adduser $WWWUSER www-data
    fi

    if [ ! -d /.composer ]; then
        mkdir /.composer
    fi

    chmod -R ugo+rw /.composer

    if [ $# -gt 0 ];then
        exec su-exec $WWWUSER "$@"
    else
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    fi

fi
